name: pos
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.14.0
  path_provider: ^2.1.2
  sqlite3_flutter_libs: ^0.5.0
  path: ^1.8.3
  flutter_bloc: ^8.1.3
  uuid: ^4.3.3
  http: ^1.2.0
  flutter_isolate: ^2.0.5-pre
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1  
  drift_dev: ^2.14.0
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
